name: 构建 Cordova 安卓 APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检查代码
        uses: actions/checkout@v4

      - name: 安装 Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装 Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 安装 Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'platforms;android-33'

      - name: 安装 Cordova
        run: npm install -g cordova

      - name: 安装插件
        run: cordova plugin add cordova-plugin-fetch

      - name: 安装依赖组件
        run: npm install

      - name: 添加安卓平台
        run: cordova platform add android --no-fetch

      - name: 构建安装包
        run: cordova build android --debug

      - name: 上传安装包
        uses: actions/upload-artifact@v4
        with:
          name: 廷琰
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk